from . import commission_policy
from . import commission_policy_line
from . import commission_policy_image
from . import commission_policy_image_line
from . import inherited_sale_order
from . import inherited_product_template
from . import inherited_res_partner
from . import inherited_product_product
from . import inherited_product_brand
from . import inherited_account_move
from . import inherited_account_move_line
from . import res_config