from . import res_config
from . import account_journal_inherit
from . import hr_allowance
from . import hr_contract_inherit
from . import hr_payroll_benefit
from . import hr_payroll_benefits_accumulated_detail
from . import hr_payroll_move
from . import hr_payslip_inherit
from . import hr_payslip_line_inherit
from . import hr_salary_rule_inherit
from . import hr_salary_tab
from . import hr_work_entry_inherit
from . import hr_employee_inherit
from . import hr_employee_bank
from . import hr_employee_degree
from . import hr_employee_dependant
from . import resource_calendar_inherit
from . import hr_employee_salary_change
from . import hr_payroll_structure_inherit
from . import hr_leave_allocation
from . import hr_leave_inherit
from . import hr_leave_type_inherit
from . import hr_department
from . import hr_payslip_payment_methods
